In [3]:
import pandas as pd

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

products = pd.read_csv("../data/raw/olist_products_dataset.csv")

sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

In [4]:
customers_clean = customers.copy()
orders_clean = orders.copy()
products_clean = products.copy()
sellers_clean = sellers.copy()
order_reviews_clean = order_reviews.copy()
order_items_clean = order_items.copy()
order_payments_clean = order_payments.copy()
geolocation_clean = geolocation.copy()
category_translation_clean = category_translation.copy()

In [5]:
order_reviews_clean[
    order_reviews_clean['review_id'].duplicated(keep=False)
].sort_values('review_id').head(20)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
54832,017808d29fd1f942d97e50184dfb4c13,8daaa9e99d60fbba579cc1c3e3bfae01,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
20621,0254bd905dc677a6078990aad3331a36,5bf226cf882c5bf4247f89a97c86f273,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44
89712,0288d42bef3dfe36930740c9588a570f,33d8795f04dd631f3480d7aaf90da3dc,3,NaN,NaN,2017-07-29 00:00:00,2017-07-31 17:11:04
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,NaN,NaN,2017-07-29 00:00:00,2017-07-31 17:11:04
47495,02aa7f5f75e964e3c7efa59a1f515281,d8e17d5f7dacf0970d316e7c03e741e8,3,NaN,NaN,2017-07-27 00:00:00,2017-07-29 15:09:50
95860,02aa7f5f75e964e3c7efa59a1f515281,db92613c074f00e53066388d48ad7512,3,NaN,NaN,2017-07-27 00:00:00,2017-07-29 15:09:50
71165,034528cb00b6bc981847acafbdf2ae0b,e1e8e3bca903de27e9a1c72b5a5795e0,1,NaN,NaN,2017-05-14 00:00:00,2017-05-15 02:17:38
81094,034528cb00b6bc981847acafbdf2ae0b,3d3742a96f24a8fe4e2e57628807e476,1,NaN,NaN,2017-05-14 00:00:00,2017-05-15 02:17:38
1988,03a6a25db577d0689440933055111897,2acfdc5131ff2cf4433e668454c9784c,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18
21587,0467560f511c516ddaa54a60edb0c291,0c995611a99f81268d859184a416f1db,5,NaN,NaN,2017-02-09 00:00:00,2017-02-14 15:58:44
24901,0467560f511c516ddaa54a60edb0c291,55b2e390d5d80ada31ad1b795ebeb087,5,NaN,NaN,2017-02-09 00:00:00,2017-02-14 15:58:44

In [6]:
order_reviews_clean['review_comment_title'] = (
    order_reviews_clean['review_comment_title'].fillna('')
)

order_reviews_clean['review_comment_message'] = (
    order_reviews_clean['review_comment_message'].fillna('')
)

In [7]:
products_clean[
    products_clean['product_category_name'].isna()
][[
    'product_id',
    'product_category_name',
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [8]:
products_clean[
    products_clean['product_weight_g'] == 0
][[
    'product_id',
    'product_category_name',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,0.0,30.0,25.0,30.0

In [9]:
order_payments_clean[
    order_payments_clean['payment_value'] <= 0
][[
    'order_id',
    'payment_type',
    'payment_installments',
    'payment_value'
]]

,order_id,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,voucher,1,0.0

In [10]:
orders_clean.groupby('order_status')[
    [
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date'
    ]
].apply(lambda x: x.isna().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [12]:
order_reviews_clean['review_comment_title'] = (
    order_reviews_clean['review_comment_title'].astype(str).str.strip()
)

order_reviews_clean['review_comment_message'] = (
    order_reviews_clean['review_comment_message'].astype(str).str.strip()
)

In [13]:
products_clean['product_category_name'] = (
    products_clean['product_category_name'].str.strip()
)

In [14]:
customers_clean['customer_city'] = (
    customers_clean['customer_city'].str.strip()
)

customers_clean['customer_state'] = (
    customers_clean['customer_state'].str.strip()
)

In [15]:
sellers_clean['seller_city'] = (
    sellers_clean['seller_city'].str.strip()
)

sellers_clean['seller_state'] = (
    sellers_clean['seller_state'].str.strip()
)

In [16]:
geolocation_clean['geolocation_city'] = (
    geolocation_clean['geolocation_city'].str.strip()
)

geolocation_clean['geolocation_state'] = (
    geolocation_clean['geolocation_state'].str.strip()
)

In [17]:
category_translation_clean['product_category_name'] = (
    category_translation_clean['product_category_name'].str.strip()
)

category_translation_clean['product_category_name_english'] = (
    category_translation_clean['product_category_name_english'].str.strip()
)

In [19]:
orders_clean.to_csv("../data/cleaned/orders_clean.csv", index=False)
customers_clean.to_csv("../data/cleaned/customers_clean.csv", index=False)
products_clean.to_csv("../data/cleaned/products_clean.csv", index=False)
sellers_clean.to_csv("../data/cleaned/sellers_clean.csv", index=False)
order_reviews_clean.to_csv("../data/cleaned/order_reviews_clean.csv", index=False)
order_items_clean.to_csv("../data/cleaned/order_items_clean.csv", index=False)
order_payments_clean.to_csv("../data/cleaned/order_payments_clean.csv", index=False)
geolocation_clean.to_csv("../data/cleaned/geolocation_clean.csv", index=False)
category_translation_clean.to_csv("../data/cleaned/category_translation_clean.csv", index=False)

In [20]:
print("orders:", len(orders), len(orders_clean))
print("customers:", len(customers), len(customers_clean))
print("products:", len(products), len(products_clean))
print("sellers:", len(sellers), len(sellers_clean))
print("order_reviews:", len(order_reviews), len(order_reviews_clean))
print("order_items:", len(order_items), len(order_items_clean))
print("order_payments:", len(order_payments), len(order_payments_clean))
print("geolocation:", len(geolocation), len(geolocation_clean))
print("category_translation:", len(category_translation), len(category_translation_clean))

orders: 99441 99441
customers: 99441 99441
products: 32951 32951
sellers: 3095 3095
order_reviews: 99224 99224
order_items: 112650 112650
order_payments: 103886 103886
geolocation: 1000163 1000163
category_translation: 71 71

In [21]:
print("ORDERS")
print(orders_clean.isna().sum())

print("\nCUSTOMERS")
print(customers_clean.isna().sum())

print("\nPRODUCTS")
print(products_clean.isna().sum())

print("\nSELLERS")
print(sellers_clean.isna().sum())

print("\nORDER REVIEWS")
print(order_reviews_clean.isna().sum())

print("\nORDER ITEMS")
print(order_items_clean.isna().sum())

print("\nORDER PAYMENTS")
print(order_payments_clean.isna().sum())

print("\nGEOLOCATION")
print(geolocation_clean.isna().sum())

print("\nCATEGORY TRANSLATION")
print(category_translation_clean.isna().sum())

ORDERS
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

CUSTOMERS
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

PRODUCTS
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

SELLERS
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

ORDER REVIEWS
review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

ORDER ITEMS
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

ORDER PAYMENTS
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

GEOLOCATION
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

CATEGORY TRANSLATION
product_category_name            0
product_category_name_english    0
dtype: int64

In [22]:
print("orders:", orders_clean['order_id'].is_unique)
print("customers:", customers_clean['customer_id'].is_unique)
print("products:", products_clean['product_id'].is_unique)
print("sellers:", sellers_clean['seller_id'].is_unique)

print("order_reviews review_id unique:",
      order_reviews_clean['review_id'].is_unique)

print("order_items composite key unique:",
      ~order_items_clean.duplicated(
          subset=['order_id', 'order_item_id']
      ).any())

print("order_payments composite key unique:",
      ~order_payments_clean.duplicated(
          subset=['order_id', 'payment_sequential']
      ).any())

orders: True
customers: True
products: True
sellers: True
order_reviews review_id unique: False
order_items composite key unique: True
order_payments composite key unique: True

In [23]:
print("Order item price <= 0:",
      (order_items_clean['price'] <= 0).sum())

print("Order item freight < 0:",
      (order_items_clean['freight_value'] < 0).sum())

print("Product weight < 0:",
      (products_clean['product_weight_g'] < 0).sum())

print("Review score outside 1-5:",
      ((order_reviews_clean['review_score'] < 1) |
       (order_reviews_clean['review_score'] > 5)).sum())

Order item price <= 0: 0
Order item freight < 0: 0
Product weight < 0: 0
Review score outside 1-5: 0

In [25]:
import os

for file in [
    "orders_clean.csv",
    "customers_clean.csv",
    "products_clean.csv",
    "sellers_clean.csv",
    "order_reviews_clean.csv",
    "order_items_clean.csv",
    "order_payments_clean.csv",
    "geolocation_clean.csv",
    "category_translation_clean.csv"
]:
    path = os.path.join("../data/cleaned", file)
    print(file, "→", os.path.exists(path))

orders_clean.csv → True
customers_clean.csv → True
products_clean.csv → True
sellers_clean.csv → True
order_reviews_clean.csv → True
order_items_clean.csv → True
order_payments_clean.csv → True
geolocation_clean.csv → True
category_translation_clean.csv → True

In [26]:
import pandas as pd
import os

files = [
    "orders_clean.csv",
    "customers_clean.csv",
    "products_clean.csv",
    "sellers_clean.csv",
    "order_reviews_clean.csv",
    "order_items_clean.csv",
    "order_payments_clean.csv",
    "geolocation_clean.csv",
    "category_translation_clean.csv"
]

for file in files:
    path = os.path.join("../data/cleaned", file)
    df = pd.read_csv(path)
    print(file, "→", len(df), "rows")

orders_clean.csv → 99441 rows
customers_clean.csv → 99441 rows
products_clean.csv → 32951 rows
sellers_clean.csv → 3095 rows
order_reviews_clean.csv → 99224 rows
order_items_clean.csv → 112650 rows
order_payments_clean.csv → 103886 rows
geolocation_clean.csv → 1000163 rows
category_translation_clean.csv → 71 rows

In [27]:
import os

print(os.path.abspath("../data/cleaned/customers_clean.csv"))

c:\Users\NASREEN\Cart2Insights\data\cleaned\customers_clean.csv

In [28]:
print(
    "Titles containing line breaks:",
    order_reviews_clean["review_comment_title"]
    .astype(str)
    .str.contains(r"[\r\n]", regex=True)
    .sum()
)

print(
    "Messages containing line breaks:",
    order_reviews_clean["review_comment_message"]
    .astype(str)
    .str.contains(r"[\r\n]", regex=True)
    .sum()
)

Titles containing line breaks: 0
Messages containing line breaks: 2710

In [29]:
order_reviews_clean.to_csv(
    "../data/cleaned/order_reviews_clean.csv",
    index=False,
    quoting=1,
    lineterminator="\r\n"
)

print("✅ order_reviews_clean.csv saved again")

✅ order_reviews_clean.csv saved again

In [30]:
import pandas as pd

test_reviews = pd.read_csv(
    "../data/cleaned/order_reviews_clean.csv"
)

print("Rows:", len(test_reviews))
print("Columns:", len(test_reviews.columns))

Rows: 99224
Columns: 7